services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: radiodb
      POSTGRES_USER: radio
      POSTGRES_PASSWORD: radiopass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000

volumes:
  postgres_data: