version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: radiodb
      POSTGRES_USER: radio
      POSTGRES_PASSWORD: radiopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: